name: Test API
on:
  workflow_call:
jobs:
    deps_and_test:
     name: dependencias y test
     runs-on: ubuntu-latest
     steps:
        - name: descargar el codigo del repositorio
          uses: actions/checkout@v4

        - name: instalar dependencias
          run: npm install

        - name: correr tests
          run: npm test